"""add_shelf_ownership

Revision ID: 2432924dd596
Revises: c2a9f6a1d0b4
Create Date: 2026-01-05 19:21:41.075222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2432924dd596'
down_revision: Union[str, Sequence[str], None] = 'c2a9f6a1d0b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_library_shares_with_user_status'), table_name='library_shares')
    # op.drop_constraint(op.f('uq_library_shares_library_user'), 'library_shares', type_='unique')
    # op.drop_index(op.f('ix_paper_shares_with_user_status'), table_name='paper_shares')
    # op.drop_constraint(op.f('uq_paper_shares_paper_user'), 'paper_shares', type_='unique')
    
    with op.batch_alter_table('shelves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('visibility', sa.String(length=16), nullable=False, server_default='private'))
        batch_op.drop_constraint('uq_shelves_name', type_='unique')
        batch_op.create_foreign_key('fk_shelves_owner_user_id', 'users', ['owner_user_id'], ['id'], ondelete='CASCADE')

    # Backfill existing rows without hard-coding a user id.
    # If users exist, assign to the first admin (or first user); otherwise keep NULL.
    op.execute(
        """
        UPDATE shelves
        SET owner_user_id = (
            SELECT id
            FROM users
            ORDER BY is_admin DESC, id ASC
            LIMIT 1
        ),
            visibility = 'private'
        WHERE owner_user_id IS NULL
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelves', schema=None) as batch_op:
        batch_op.drop_constraint('fk_shelves_owner_user_id', type_='foreignkey')
        batch_op.create_unique_constraint(op.f('uq_shelves_name'), ['name'])
        batch_op.drop_column('visibility')
        batch_op.drop_column('owner_user_id')
    # ### end Alembic commands ###
