"""init

Revision ID: 3bcc51a3ee9b
Revises: 
Create Date: 2026-01-04 16:12:48.571940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bcc51a3ee9b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # This project historically relied on an existing DB file; many follow-up
    # migrations assume the 'papers' table already exists.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    if 'papers' not in existing_tables:
        op.create_table(
            'papers',
            sa.Column('id', sa.String(length=64), primary_key=True),
            sa.Column('title', sa.String(length=512), nullable=False),
            sa.Column('subtitle', sa.String(length=512), nullable=False, server_default=''),
            sa.Column('file_path', sa.String(length=1024), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_table('papers')
    except Exception:
        pass
    # ### end Alembic commands ###
