"""library_meta

Revision ID: a7c5f34073f3
Revises: 37738c38138f
Create Date: 2026-01-04 16:58:11.497992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c5f34073f3'
down_revision: Union[str, Sequence[str], None] = '37738c38138f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite cannot add a NOT NULL column without a DEFAULT.
    with op.batch_alter_table('libraries') as batch:
        batch.add_column(sa.Column('description', sa.String(length=1024), nullable=False, server_default=''))
        batch.add_column(sa.Column('icon', sa.String(length=64), nullable=False, server_default='menu_book'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('libraries', 'icon')
    op.drop_column('libraries', 'description')
    # ### end Alembic commands ###
